services:
  cs2_modded_server:
    image: cs2-modded-server
    container_name: cs2-modded-server
    env_file:
      - .env
    volumes:
      - cs2-volume:/home/steam/
      - type: bind
        source: ./custom_files
        target: /home/custom_files/
      - type: bind
        source: ./game
        target: /home/game/
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/tcp"
      - "27020:27020/udp"
    cpu_count: 2
    mem_limit: 3500m
    # command: tail -F anything
  mysql:
    image: mysql:5.7
    container_name: cs2-mysql
    env_file:
      - .env
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  cs2-volume:
  mysql-volume:
